exec(open('util.py').read())
def log(inp):
	
	"""
	ope.append("pro")
	ope.append("ins")
	ope.append("go2")
	ope.append("caf")
	ope.append("kee")
	ope.append("gma")
	ope.append("twi")
	ope.append("fac")
	ope.append("rel")	
	"""

	mas = []
	#info mas.append(['','Mikael', 'Sandstedt', '07/30/90', '5403223655', '', ''])
	mas.append(['rel','reddit', 'Emergency_Zebra_5972', 'Zebra_59', 'https://www.reddit.com/', 'reddit', 'dodgers45@proton.me'])
	mas.append(['fac','facebook', 'violin78@protonmail.com', 'Viovio1!', 'https://facebook.com', '', ''])
	mas.append(['twi','twitter', 'media788788@gmail.com', 'Medmed1!', 'https://twitter.com', 'twitter', 'violin788'])
	mas.append(['pro','protonmail', 'violin78', 'viovio', 'https://mail.protonmail.com/login', 'protonmail', ''])


	mas.append(['','wordpress', 'violin78@protonmail.com', 'Viovio1!', 'https://wordpress.com/log-in', 'wordpress', ''])
	mas.append(['','wix', 'violin78@protonmail.com', 'Viovio1!', 'https://users.wix.com/signin?view=sign-up&sendEmail=true&originUrl=https:%2F%2Fwww.wix.com%2F&loginCompName=SignUp_H&postSignUp=https:%2F%2Fwww.wix.com%2Fnew%2Fintro%2F&referralInfo=SignUp_H&postLogin=https:%2F%2Fmanage.wix.com%2Faccount%2Froute&loginDialogContext=login&forceRender=true', 'wix', ''])
	mas.append(['','', '', '', '', '', ''])
	mas.append(['','alpaca', 'violin78@protonmail.com', 'viovioviovio', '', '', ''])
	mas.append(['','', 'violin78@protonmail.com', 'Viovioviovio', 'Viovioviovio1!', '', ''])
	mas.append(['','amazon', 'media788788@gmail.com', 'Medmed1!', 'https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2Fyour-account%3Fref_%3Dnav_ya_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&', 'amazon', ''])
	mas.append(['','amazon order', 'violin78@protonmail.com', 'Viovio1!', 'https://www.amazon.com/gp/css/order-history?ref_=nav_AccountFlyout_orders', 'amazon order', ''])
	mas.append(['','anthem', 'violin78', 'Vivivi1!', 'https://mss.anthem.com/va/secure/claims.html#/claims', 'anthem', ''])
	mas.append(['','anthem', 'violin78', 'Medmed1!', 'https://mss.anthem.com/va/secure/claims.html#/claims', 'anthem', ''])
	mas.append(['','ant - medic', 'medicaid67', 'Medmed1!', 'https://commonhelp.dss.virginia.gov/CASWeb/faces/loginCAS.xhtml?MODULE_NAME=CMB&SERVICE_PROVIDER=COMMON_HELP&LANGUAGE=EN', 'ant - medic', ''])
	mas.append(['','atl - card', '4435470506506030', 'Mikael', '', 'atl - card', '4435470506506030'])
	mas.append(['','atlantic union', 'mikaels', 'Vvbd63Vvbd63!', 'https://www.atlanticunionbank.com/personal/online-mobile-banking/online-banking', 'atlantic union', ''])
	mas.append(['','atlantic union', 'atlatl', 'Medmed1!', 'https://www.atlanticunionbank.com/personal/online-mobile-banking/online-banking', 'atlantic union', 'media788788@gmail.com'])
	mas.append(['','craigslist computer', '', '', 'https://fredericksburg.craigslist.org/d/computers/search/sya?sort=priceasc&', 'craigslist computer', ''])
	mas.append(['','craigslist fbg', 'violin78@protonmail.com', 'Viovio1!', 'http://fredericksburg.craigslist.org', 'craigslist fbg', ''])
	mas.append(['','craigslist login', 'violin78@protonmail.com', 'Viovio1!', 'https://accounts.craigslist.org/login/home', 'craigslist login', 'Mikael'])
	mas.append(['','data.nasdaq', 'cello34@protonmail.colm', 'Celcelcelcel1!', 'token', 'xmefpKkxybsUgCpGhtqX', ''])
	mas.append(['','dmv', '212331006', 'Vvbd63Vvbd63#', 'https://www.dmv.virginia.gov/apps/webtrans/pin_maint/pin_logon.aspx', 'dmv', 'Sandstedt'])
	mas.append(['','ebay', 'media788788@gmail.com', 'Medmed1!', 'https://signin.ebay.com/ws/eBayISAPI.dll?SignIn&ru=https%3A%2F%2Fwww.ebay.com%2F', 'ebay', ''])
	mas.append(['','facebook', 'violin78@protonmail.com', 'Viovio1!', 'https://facebook.com', 'facebook', 'Haynesville'])
	mas.append(['','fedex', 'violin78', 'Viovio1!', 'https://www.fedex.com/fcl/?appName=fclfsm&locale=us_en&step3URL=https%3A%2F%2Fwww.fedex.com%2Fshipping%2FshipEntryAction.do%3Fmethod%3DdoRegistration%26link%3D1%26locale%3Den_US%26urlparams%3Dus%26sType%3DF&returnurl=https%3A%2F%2Fwww.fedex.com%2Fshipping%2FshipEntryAction.do%3Fmethod%3DdoEntry%26link%3D1%26locale%3Den_US%26urlparams%3Dus%26sType%3DF&programIndicator=0', 'fedex', 'Virginia'])
	mas.append(['','gettr', 'violin789', 'viovio', 'https://gettr.com/login', 'gettr', '22472'])
	mas.append(['','google drive', 'media475634@gmail.com', 'Medmed1!', 'https://drive.google.com', 'google drive', ''])
	mas.append(['','google drive', 'media788788@gmail.com', 'Medmed1!', 'https://drive.google.com', 'google drive', ''])
	mas.append(['','google drive', 'desk544', 'Desdes1!', 'https://drive.google.com', 'google drive', ''])
	mas.append(['','hardees', 'violin78@protonmail.com', 'Viovio1!', 'https://order.hardees.com/account/login', 'hardees', ''])
	mas.append(['','healow', 'media788788@gmail.com', 'Medmed1!', 'https://mycw91.ecwcloud.com/portal12182/jsp/100mp/login_otp.jsp', 'healow', ''])
	mas.append(['','hom', 'violin78@protonmail.com', 'Vioviovio11!', 'https://mycw91.ecwcloud.com/portal12182/jsp/100mp/login_otp.jsp', 'healow', ''])
	#home depot

	mas.append(['','iex', 'violin78@protonmail.com', 'Viovio1!', 'https://iexcloud.io/docs/api/', 'iex', ''])
	mas.append(['','instacart', 'violin78@protonmail.com', 'Viovio1!', 'https://www.instacart.com/?utm_medium=sem&utm_source=instacart_google&utm_campaign=ad_demand_search_brand_us-dc-washington_exact_us&utm_content=accountid-1732890876_campaignid-10023670068_adgroupid-102598081362_device-c_adid-517871920239_network-g&utm_term=matchtype-e_keyword-instacart_targetid-aud-300134955297:kwd-297369219725_locationid-9008196&kskwid=6068828&ksadid=6238859&gclid=CjwKCAjwwqaGBhBKEiwAMk-FtDtCQJT5HBbMdPa98OQ1z0KuLZAssjq3nMlhhP2Xb14Yco_1VzEuVhoCjG8QAvD_BwE', 'instacart', ''])
	mas.append(['','instagram', 'media788788@gmail.com', 'Medmed1!', 'https://www.instagram.com/accounts/login/', 'instagram', ''])
	mas.append(['','labcorp', 'violin78@protonmail.com', 'Viovio1!', 'https://patient.labcorp.com/', 'labcorp', ''])
	mas.append(['','linkedin', 'violin78@protonmail.com', 'Viovio1!', 'https://www.linkedin.com/login?session_redirect=https%3A%2F%2Fwww%2Elinkedin%2Ecom%2Fin%2Felle-reeve-491973a5&fromSignIn=true&trk=public_profile_nav-header-signin', 'linkedin', ''])
	mas.append(['','lowes', 'violin78@protonmail.com', 'Viovio1!', 'https://www.lowes.com/u/login/oauth2/authorize?redirect_uri=https%3A%2F%2Fwww.lowes.com%2Fu%2Flogin%2Foauth2%2Fpostauthorize&scope=general-digital-access&client_id=loweswebclient&state=OUt1cThmeUNNWlF5YnNsUFd6VTdJUDVqQWpBR0tiRlVQN0dITkFnQncwQkFDWHV3dGtjb0FxcVFkendZQzRZUw%3D%3D&code_challenge=Ucqo4JD-2lqEvdChN-NgxHAwfag5sRbnwAjYYCEIYnw&code_challenge_method=S256&redirect=', 'lowes', ''])
	mas.append(['','mwh', 'mwhos', 'mwhos123', 'https://mychart.mwhc.com/mychart/Billing/Details?ID=WP-24BZ0G8iQup-2B0YpR6dV6umeQ-3D-3D-24HyCPRBVi9Tsd0DWVi57-2Bv0ZSpX9HMaYHmhQB7Yh07WI-3D&Context=WP-24kaa7uki37RKmJYXx9C3DdQ-3D-3D-24w-2B8Fh5dBnlLOcSy9SzR8Eu1gObDNVjvEi30vpI14S7s-3D', 'mwh', ''])
	mas.append(['','paypal', 'gocubs7@protonmail.com', 'Vvbd63Vvbd63', 'paypal.com', 'paypal', 'Viovio1!'])
	mas.append(['','polygonscan', 'violin78', 'Viovio1!', 'https://polygonscan.com/register', 'polygonscan', ''])
	mas.append(['','protonmail', 'cello34', 'celcel', 'https://mail.protonmail.com/login', 'protonmail', ''])
	mas.append(['','protonmail', 'gocubs7', 'cubwsw', 'https://mail.protonmail.com/login', 'protonmail', ''])
	mas.append(['','protonmail', 'nova56', 'novnov', 'https://mail.protonmail.com/login', 'protonmail', ''])
	mas.append(['','protonmail', 'violin78', 'viovio', 'https://mail.protonmail.com/login', 'protonmail', ''])
	mas.append(['','quest', 'violin78@protonmail.com', 'Viovio1!', 'https://myquest.questdiagnostics.com/dashboard', 'quest', ''])
	mas.append(['','quora', 'table65@mail.com', 'Tabtab1!', 'https://quora.com', 'quora', ''])
	mas.append(['','reddit', 'pizza_4_all_', 'cheesepizza', 'https://www.reddit.com/', 'reddit', ''])
	#Emergency_Zebra_5972,Zebra_59
	mas.append(['','rumble', 'violin78@protonmail.com', 'Viovio1!', '', 'rumble', ''])
	mas.append(['','skype - my account', 'violin78@mail.com', 'vioviovio1', 'https://secure.skype.com/portal/overview', 'skype - my account', ''])
	mas.append(['','skype - web', 'violin78@mail.com', 'vioviovio1', 'https://web.skype.com/', 'skype - web', ''])
	mas.append(['','swe-mas', 'Mikael Sandstedt', '5168 1531 3323 9073,04-24,818', '', 'swe-mas', ''])
	mas.append(['','swedbank', '199007305411', '70197019', 'https://online.swedbank.se/app/ib/logga-in', 'swedbank', ''])
	mas.append(['','target', 'violin78@protonmail.com', 'Viovio1!', 'https://login.target.com/gsp/static/v1/login/?client_id=ecom-web-1.0.0&ui_namespace=ui-default&back_button_action=browser&keep_me_signed_in=true&kmsi_default=false&actions=create_session_signin', 'target', ''])
	mas.append(['','twitter', 'media788788@gmail.com', 'Medmed1!', 'https://twitter.com', 'twitter', 'violin8374'])
	mas.append(['','unhcr,1', '1,violin78@protonmail.com', '199007305411', 'https://sverigeforunhcr.se/stod-oss/julklappar/gava', 'unhcr,1', ''])
	mas.append(['','unhcr', '1', 'violin78@protonmail.com', '199007305411', 'unhcr', '731431617'])
	mas.append(['','ups', 'media788788@gmail.com', 'Medmedmedmed1!', 'https://www.ups.com/lasso/login?loc=en_US', 'ups', ''])
	mas.append(['','ups', 'violin78@protonmail.com', 'Medmedmedmed1!', 'https://www.ups.com/lasso/login?loc=en_US', 'ups', ''])
	mas.append(['','vhc', 'cello34', 'Celcel1!', 'https://myvhc.virginiahospitalcenter.com/MyChartPRD/inside.asp?mode=visitsummary&csn=WP-24Ybpe8B2Q1nzR-2BprK7LsTlA-3D-3D-24PK0xxqFuRFEP4VSywnjnUGlue1aB9X9q5IgIOZ9CNJo-3D', 'vhc', ''])
	mas.append(['','walmart', 'violin78@protonmail.com', 'Viovio1!', 'https://www.walmart.com/account/login?vid=oaoh&tid=0&returnUrl=%2F', 'walmart', ''])
	mas.append(['','wix', 'violin78@protonmail.com', 'Viovio1!', 'https://users.wix.com/signin?view=sign-up&sendEmail=true&originUrl=https:%2F%2Fwww.wix.com%2F&loginCompName=SignUp_H&postSignUp=https:%2F%2Fwww.wix.com%2Fnew%2Fintro%2F&referralInfo=SignUp_H&postLogin=https:%2F%2Fmanage.wix.com%2Faccount%2Froute&loginDialogContext=login&forceRender=true', 'wix', ''])
	mas.append(['','wordpress', 'violin78@protonmail.com', 'Viovio1!', 'https://wordpress.com/log-in', 'wordpress', ''])


inp = []
log(inp)