exec(open('util.py').read())
main_page_html = load_data(["stock_new.html"])
def stock_new(inp):
	from flask import Flask, render_template
	app = Flask(__name__)
	@app.route('/')
	def index():
	    #html = load_data(["stock_new.html"])
	    return (main_page_html)



	@app.route('/handle_post', methods=['POST'])
	def process(): 
		return ("meow")

	if __name__ == '__main__':
	    port = 5000
	    url = "http://localhost:"+str(port)+"/"
	    subprocess_open([0,url,"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"])
	    app.run(debug=True, port=port)


 		
inp = []
stock_new(inp)


"""

	@app.route('/your_route', methods=['GET', 'POST'])
	def your_function():
	    if request.method == 'POST':
	        # Handle POST request logic here
	        # ...
	        return 'Form submitted successfully!'
	    else:
	        # Handle GET request (display form)
	        return render_template('your_template.html')	    



	    if request.method == 'POST':
	        name = request.form['name']
	        # Do something with the data
	        return redirect(url_for('greet', name=name))
	    else:
	    """




exec(open('util.py').read())
import requests
import json
def earnings_dates_polygon(inputs):
	#earnings_dates_polygon([stocks])
	stocks = inputs[0]
	stocks.sort()
	for a,val in enumerate(stocks):
		stocks[a]=val.upper()
	earn_list = os.listdir("earn")
	print(earn_list)
	save_affix = "_earnings_dates_polygon.json"
	to_get = []
	for a,val in enumerate(stocks):
		symbol = val	
		match = symbol+save_affix
		print(match)
		if match in earn_list:
			continue
		else: 
			to_get.append(symbol)
	print(to_get)
	#end()
	for a,val in enumerate(to_get):
		symbol = val	
		url = "https://api.polygon.io/vX/reference/financials?ticker="+symbol+"&limit=50&apiKey=65JaxrhDSYET1StvPxZy1KgpnttWna98"
		response = requests.get(url)
		data = response.json()
		save_folder = "earn\\"
		save_file = save_folder+symbol+save_affix
		with open(save_file, 'w') as f:
			json.dump(data, f, indent=2)
			print(str(a)+" of "+str(len(to_get)))
			print(f"Data saved to {save_file}")
		if a+1==len(to_get):
			continue
		timer([20])
	

stocks = []
stocks.append("MMM")
stocks.append("AOS")
stocks.append("ABT")
stocks.append("ABBV")
stocks.append("ACN")
stocks.append("ADBE")
stocks.append("AMD")
stocks.append("AES")
stocks.append("AFL")
stocks.append("A")
stocks.append("APD")
stocks.append("ABNB")
stocks.append("AKAM")
stocks.append("ALB")
stocks.append("ARE")
stocks.append("ALGN")
stocks.append("ALLE")
stocks.append("LNT")
stocks.append("ALL")
stocks.append("GOOGL")
stocks.append("GOOG")
stocks.append("MO")
stocks.append("AMZN")
stocks.append("AMCR")
stocks.append("AEE")
stocks.append("AAL")
stocks.append("AEP")
stocks.append("AXP")
stocks.append("AIG")
stocks.append("AMT")
stocks.append("AWK")
stocks.append("AMP")
stocks.append("AME")
stocks.append("AMGN")
stocks.append("APH")
stocks.append("ADI")
stocks.append("ANSS")
stocks.append("AON")
stocks.append("APA")
stocks.append("AAPL")
stocks.append("AMAT")
stocks.append("APTV")
stocks.append("ACGL")
stocks.append("ADM")
stocks.append("ANET")
stocks.append("AJG")
stocks.append("AIZ")
stocks.append("T")
stocks.append("ATO")
stocks.append("ADSK")
stocks.append("ADP")
stocks.append("AZO")
stocks.append("AVB")
stocks.append("AVY")
stocks.append("AXON")
stocks.append("BKR")
stocks.append("BALL")
stocks.append("BAC")
stocks.append("BK")
stocks.append("BBWI")
stocks.append("BAX")
stocks.append("BDX")
stocks.append("BRK.B")
stocks.append("BBY")
stocks.append("BIO")
stocks.append("TECH")
stocks.append("BIIB")
stocks.append("BLK")
stocks.append("BX")
stocks.append("BA")
stocks.append("BKNG")
stocks.append("BWA")
stocks.append("BSX")
stocks.append("BMY")
stocks.append("AVGO")
stocks.append("BR")
stocks.append("BRO")
stocks.append("BF.B")
stocks.append("BLDR")
stocks.append("BG")
stocks.append("BXP")
stocks.append("CDNS")
stocks.append("CZR")
stocks.append("CPT")
stocks.append("CPB")
stocks.append("COF")
stocks.append("CAH")
stocks.append("KMX")
stocks.append("CCL")
stocks.append("CARR")
stocks.append("CTLT")
stocks.append("CAT")
stocks.append("CBOE")
stocks.append("CBRE")
stocks.append("CDW")
stocks.append("CE")
stocks.append("COR")
stocks.append("CNC")
stocks.append("CNP")
stocks.append("CF")
stocks.append("CHRW")
stocks.append("CRL")
stocks.append("SCHW")
stocks.append("CHTR")
stocks.append("CVX")
stocks.append("CMG")
stocks.append("CB")
stocks.append("CHD")
stocks.append("CI")
stocks.append("CINF")
stocks.append("CTAS")
stocks.append("CSCO")
stocks.append("C")
stocks.append("CFG")
stocks.append("CLX")
stocks.append("CME")
stocks.append("CMS")
stocks.append("KO")
stocks.append("CTSH")
stocks.append("CL")
stocks.append("CMCSA")
stocks.append("CAG")
stocks.append("COP")
stocks.append("ED")
stocks.append("STZ")
stocks.append("CEG")
stocks.append("COO")
stocks.append("CPRT")
stocks.append("GLW")
stocks.append("CPAY")
stocks.append("CTVA")
stocks.append("CSGP")
stocks.append("COST")
stocks.append("CTRA")
stocks.append("CRWD")
stocks.append("CCI")
stocks.append("CSX")
stocks.append("CMI")
stocks.append("CVS")
stocks.append("DHR")
stocks.append("DRI")
stocks.append("DVA")
stocks.append("DAY")
stocks.append("DECK")
stocks.append("DE")
stocks.append("DAL")
stocks.append("DVN")
stocks.append("DXCM")
stocks.append("FANG")
stocks.append("DLR")
stocks.append("DFS")
stocks.append("DG")
stocks.append("DLTR")
stocks.append("D")
stocks.append("DPZ")
stocks.append("DOV")
stocks.append("DOW")
stocks.append("DHI")
stocks.append("DTE")
stocks.append("DUK")
stocks.append("DD")
stocks.append("EMN")
stocks.append("ETN")
stocks.append("EBAY")
stocks.append("ECL")
stocks.append("EIX")
stocks.append("EW")
stocks.append("EA")
stocks.append("ELV")
stocks.append("EMR")
stocks.append("ENPH")
stocks.append("ETR")
stocks.append("EOG")
stocks.append("EPAM")
stocks.append("EQT")
stocks.append("EFX")
stocks.append("EQIX")
stocks.append("EQR")
stocks.append("ESS")
stocks.append("EL")
stocks.append("ETSY")
stocks.append("EG")
stocks.append("EVRG")
stocks.append("ES")
stocks.append("EXC")
stocks.append("EXPE")
stocks.append("EXPD")
stocks.append("EXR")
stocks.append("XOM")
stocks.append("FFIV")
stocks.append("FDS")
stocks.append("FICO")
stocks.append("FAST")
stocks.append("FRT")
stocks.append("FDX")
stocks.append("FIS")
stocks.append("FITB")
stocks.append("FSLR")
stocks.append("FE")
stocks.append("FI")
stocks.append("FMC")
stocks.append("F")
stocks.append("FTNT")
stocks.append("FTV")
stocks.append("FOXA")
stocks.append("FOX")
stocks.append("BEN")
stocks.append("FCX")
stocks.append("GRMN")
stocks.append("IT")
stocks.append("GE")
stocks.append("GEHC")
stocks.append("GEV")
stocks.append("GEN")
stocks.append("GNRC")
stocks.append("GD")
stocks.append("GIS")
stocks.append("GM")
stocks.append("GPC")
stocks.append("GILD")
stocks.append("GPN")
stocks.append("GL")
stocks.append("GDDY")
stocks.append("GS")
stocks.append("HAL")
stocks.append("HIG")
stocks.append("HAS")
stocks.append("HCA")
stocks.append("DOC")
stocks.append("HSIC")
stocks.append("HSY")
stocks.append("HES")
stocks.append("HPE")
stocks.append("HLT")
stocks.append("HOLX")
stocks.append("HD")
stocks.append("HON")
stocks.append("HRL")
stocks.append("HST")
stocks.append("HWM")
stocks.append("HPQ")
stocks.append("HUBB")
stocks.append("HUM")
stocks.append("HBAN")
stocks.append("HII")
stocks.append("IBM")
stocks.append("IEX")
stocks.append("IDXX")
stocks.append("ITW")
stocks.append("INCY")
stocks.append("IR")
stocks.append("PODD")
stocks.append("INTC")
stocks.append("ICE")
stocks.append("IFF")
stocks.append("IP")
stocks.append("IPG")
stocks.append("INTU")
stocks.append("ISRG")
stocks.append("IVZ")
stocks.append("INVH")
stocks.append("IQV")
stocks.append("IRM")
stocks.append("JBHT")
stocks.append("JBL")
stocks.append("JKHY")
stocks.append("J")
stocks.append("JNJ")
stocks.append("JCI")
stocks.append("JPM")
stocks.append("JNPR")
stocks.append("K")
stocks.append("KVUE")
stocks.append("KDP")
stocks.append("KEY")
stocks.append("KEYS")
stocks.append("KMB")
stocks.append("KIM")
stocks.append("KMI")
stocks.append("KKR")
stocks.append("KLAC")
stocks.append("KHC")
stocks.append("KR")
stocks.append("LHX")
stocks.append("LH")
stocks.append("LRCX")
stocks.append("LW")
stocks.append("LVS")
stocks.append("LDOS")
stocks.append("LEN")
stocks.append("LLY")
stocks.append("LIN")
stocks.append("LYV")
stocks.append("LKQ")
stocks.append("LMT")
stocks.append("L")
stocks.append("LOW")
stocks.append("LULU")
stocks.append("LYB")
stocks.append("MTB")
stocks.append("MRO")
stocks.append("MPC")
stocks.append("MKTX")
stocks.append("MAR")
stocks.append("MMC")
stocks.append("MLM")
stocks.append("MAS")
stocks.append("MA")
stocks.append("MTCH")
stocks.append("MKC")
stocks.append("MCD")
stocks.append("MCK")
stocks.append("MDT")
stocks.append("MRK")
stocks.append("META")
stocks.append("MET")
stocks.append("MTD")
stocks.append("MGM")
stocks.append("MCHP")
stocks.append("MU")
stocks.append("MSFT")
stocks.append("MAA")
stocks.append("MRNA")
stocks.append("MHK")
stocks.append("MOH")
stocks.append("TAP")
stocks.append("MDLZ")
stocks.append("MPWR")
stocks.append("MNST")
stocks.append("MCO")
stocks.append("MS")
stocks.append("MOS")
stocks.append("MSI")
stocks.append("MSCI")
stocks.append("NDAQ")
stocks.append("NTAP")
stocks.append("NFLX")
stocks.append("NEM")
stocks.append("NWSA")
stocks.append("NWS")
stocks.append("NEE")
stocks.append("NKE")
stocks.append("NI")
stocks.append("NDSN")
stocks.append("NSC")
stocks.append("NTRS")
stocks.append("NOC")
stocks.append("NCLH")
stocks.append("NRG")
stocks.append("NUE")
stocks.append("NVDA")
stocks.append("NVR")
stocks.append("NXPI")
stocks.append("ORLY")
stocks.append("OXY")
stocks.append("ODFL")
stocks.append("OMC")
stocks.append("ON")
stocks.append("OKE")
stocks.append("ORCL")
stocks.append("OTIS")
stocks.append("PCAR")
stocks.append("PKG")
stocks.append("PANW")
stocks.append("PARA")
stocks.append("PH")
stocks.append("PAYX")
stocks.append("PAYC")
stocks.append("PYPL")
stocks.append("PNR")
stocks.append("PEP")
stocks.append("PFE")
stocks.append("PCG")
stocks.append("PM")
stocks.append("PSX")
stocks.append("PNW")
stocks.append("PNC")
stocks.append("POOL")
stocks.append("PPG")
stocks.append("PPL")
stocks.append("PFG")
stocks.append("PG")
stocks.append("PGR")
stocks.append("PLD")
stocks.append("PRU")
stocks.append("PEG")
stocks.append("PTC")
stocks.append("PSA")
stocks.append("PHM")
stocks.append("QRVO")
stocks.append("PWR")
stocks.append("QCOM")
stocks.append("DGX")
stocks.append("RL")
stocks.append("RJF")
stocks.append("RTX")
stocks.append("O")
stocks.append("REG")
stocks.append("REGN")
stocks.append("RF")
stocks.append("RSG")
stocks.append("RMD")
stocks.append("RVTY")
stocks.append("ROK")
stocks.append("ROL")
stocks.append("ROP")
stocks.append("ROST")
stocks.append("RCL")
stocks.append("SPGI")
stocks.append("CRM")
stocks.append("SBAC")
stocks.append("SLB")
stocks.append("STX")
stocks.append("SRE")
stocks.append("NOW")
stocks.append("SHW")
stocks.append("SPG")
stocks.append("SWKS")
stocks.append("SJM")
stocks.append("SW")
stocks.append("SNA")
stocks.append("SOLV")
stocks.append("SO")
stocks.append("LUV")
stocks.append("SWK")
stocks.append("SBUX")
stocks.append("STT")
stocks.append("STLD")
stocks.append("STE")
stocks.append("SYK")
stocks.append("SMCI")
stocks.append("SYF")
stocks.append("SNPS")
stocks.append("SYY")
stocks.append("TMUS")
stocks.append("TROW")
stocks.append("TTWO")
stocks.append("TPR")
stocks.append("TRGP")
stocks.append("TGT")
stocks.append("TEL")
stocks.append("TDY")
stocks.append("TFX")
stocks.append("TER")
stocks.append("TSLA")
stocks.append("TXN")
stocks.append("TXT")
stocks.append("TMO")
stocks.append("TJX")
stocks.append("TSCO")
stocks.append("TT")
stocks.append("TDG")
stocks.append("TRV")
stocks.append("TRMB")
stocks.append("TFC")
stocks.append("TYL")
stocks.append("TSN")
stocks.append("USB")
stocks.append("UBER")
stocks.append("UDR")
stocks.append("ULTA")
stocks.append("UNP")
stocks.append("UAL")
stocks.append("UPS")
stocks.append("URI")
stocks.append("UNH")
stocks.append("UHS")
stocks.append("VLO")
stocks.append("VTR")
stocks.append("VLTO")
stocks.append("VRSN")
stocks.append("VRSK")
stocks.append("VZ")
stocks.append("VRTX")
stocks.append("VTRS")
stocks.append("VICI")
stocks.append("V")
stocks.append("VST")
stocks.append("VMC")
stocks.append("WRB")
stocks.append("GWW")
stocks.append("WAB")
stocks.append("WBA")
stocks.append("WMT")
stocks.append("DIS")
stocks.append("WBD")
stocks.append("WM")
stocks.append("WAT")
stocks.append("WEC")
stocks.append("WFC")
stocks.append("WELL")
stocks.append("WST")
stocks.append("WDC")
stocks.append("WY")
stocks.append("WMB")
stocks.append("WTW")
stocks.append("WYNN")
stocks.append("XEL")
stocks.append("XYL")
stocks.append("YUM")
stocks.append("ZBRA")
stocks.append("ZBH")
stocks.append("ZTS")

earnings_dates_polygon([stocks])